### PR TITLE
Various arch components support fixes

### LINKED ISSUE #93: AndroidLifecycleScopeProvider do not work
I tried the `AndroidLifecycleScopeProvider` implementation with the following code, but it doesn't work and keep emitting when onStop()` is called.

```kotlin
override fun onStart() {
    super.onStart()
    Observable.interval(0, 1, TimeUnit.SECONDS)
      .doOnDispose { println("dispose") }
      .to(ObservableScoper(AndroidLifecycleScopeProvider.from(this)))
      .subscribe {
        println("emit:" + it)
      }
  }

  override fun onStop() {
    super.onStop()
    println("onStop")
  }
```

Thanks.

### PR DESCRIPTION
**Pull request by hzsweers**
This is a few miscellaneous arch components fixes:
- Enabled releases now
- Fix a deprecated implementation to use `LifecycleOwner`
- Make tests more comprehensive and realistic
- Fix #93 by offsetting backfilling up one. See issue there for more info, but the gist is that lifecycle `State`s are always the preceding event until after the callback is completed. A little confusing, but we can hide the weirdness under the hood as implementation detail.

### CODE REVIEW

File: autodispose-android-archcomponents/src/androidTest/java/com/uber/autodispose/android/lifecycle/AndroidLifecycleTest.java [hunk 1]
```diff
@@ -75,38 +71,112 @@
     o.assertNoMoreEvents();
   }
 
-  @Test public void observable_offMainThread_shouldFail() {
-    RecordingObserver<Integer> o = new RecordingObserver<>(LOGGER);
-    PublishSubject<Integer> subject = PublishSubject.create();
+  @Test @UiThreadTest public void observable_createDestroy() {
```
Comment (AttwellBrian) [inline autodispose-android-archcomponents/src/androidTest/java/com/uber/autodispose/android/lifecycle/AndroidLifecycleTest.java]: Why `UiThreadTest`?

**Comment by hzsweers** [comment]
> Why crash when off background thread?

[Offensive programming](https://en.wikipedia.org/wiki/Offensive_programming), arch components lifecycle handling only supports main thread (including `@MainThread` annotations on the methods).
